<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NuGetAudit>false</NuGetAudit>
    <BaseIntermediateOutputPath Condition="'$(IsolatedBuildRoot)' != ''">$(IsolatedBuildRoot)/obj/$(MSBuildProjectName)/</BaseIntermediateOutputPath>
    <BaseOutputPath Condition="'$(IsolatedBuildRoot)' != ''">$(IsolatedBuildRoot)/bin/$(MSBuildProjectName)/</BaseOutputPath>
  </PropertyGroup>
</Project>
