<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Confluent.Kafka" Version="2.15.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.4" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.4" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.4.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.0" />
    <PackageVersion Include="OpenTelemetry" Version="1.18.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.18.0" />
    <PackageVersion Include="Spectre.Console" Version="0.55.0" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageVersion Include="Testcontainers" Version="4.15.0" />
    <PackageVersion Include="Testcontainers.Kafka" Version="4.15.0" />
    <PackageVersion Include="TUnit" Version="1.66.27" />
  </ItemGroup>
</Project>
